### ISSUE TITLE
Dead menu link

### ISSUE THREAD

**Issue by LeoVie** [usebruno/bruno-docs-legacy#112]
In the menu, there is a navigation point "index" in the "Introduction" section. Clicking on it does not have an effect, as there is no "index" page in this section.

I think, this is a leftover from https://github.com/usebruno/bruno-docs/commit/0787a71ea60b1b4c5bec99bdc9f636c4bb5137b9

<img width="250" alt="grafik" src="https://github.com/user-attachments/assets/aa17c4a3-e5b4-48fa-8956-fe785fefc801">

I will create a PR for this issue.

**Comment by ganesh-bruno** [comment]
This page is now present in docs: https://docs.usebruno.com/introduction/feedback-community
Closing this issue.
