### ISSUE TITLE
Feedback for “JavaScript Reference”

### ISSUE THREAD

**Issue by jstevenson** [usebruno/bruno-docs-legacy#131]
The "JavaScript Reference” page is inaccessible from the left nav and from the bottom navigation at https://docs.usebruno.com/testing/assertions. It appears that the page is linked to "#", and does not exist at https://docs.usebruno.com/testing/javascript-reference.

**Comment by ganesh-bruno** [comment]
Hey @jstevenson,

Thanks for raising this issue. 
We have fixed the broken link in the `javascript reference` document. 
You can checkout here - [API Testing](https://docs.usebruno.com/testing/introduction)
