### ISSUE TITLE
Feedback for “Using secrets”

### ISSUE THREAD

**Issue by sikorka** [usebruno/bruno-docs-legacy#77]
A typo on the page https://docs.usebruno.com/secrets-management/hashicorp-vault/using-secrets: 
seperated > sepArated 

<img width="1135" alt="Screenshot 2024-07-21 at 14 48 23" src="https://github.com/user-attachments/assets/8b43dcdf-6ff6-4de3-b8c7-da1fde8bf4aa">

**Comment by sikorka** [comment]
Implemented in #82

**Comment by ganesh-bruno** [comment]
PR Merged. Thanks @sikorka !
