### ISSUE TITLE
Readme missing steps

### ISSUE THREAD

**Issue by sikorka** [usebruno/bruno-docs-legacy#80]
When someone new to `bruno-docs`, like me, is trying to run it locally, it does not work following instructions in Readme. 

After going through `Next.js` documentation I figure `readme.md` is missing steps for installing packages: 
<img width="287" alt="Screenshot 2024-07-21 at 13 06 51" src="https://github.com/user-attachments/assets/f5299ecc-d342-4ca5-af9e-528631936457">

Something like this would be handy: 
<img width="467" alt="Screenshot 2024-07-21 at 13 05 01" src="https://github.com/user-attachments/assets/b0201557-507b-4ebb-ac74-071bee47066a">

**Comment by ganesh-bruno** [comment]
PR Merged. Thanks @sikorka !
